import { Inter } from 'next/font/google';

import StyledComponentsRegistry from '@/components/StyledComponentsRegistry/StyledComponentsRegistry';
import GlobalStyles from '@/components/GlobalStyles/GlobalStyles';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          {children}
          <GlobalStyles />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
